language: r
warnings_are_errors: true
sudo: required
env:
  global:
    - TRAVIS_NODE_VERSION="4"
    - NOT_CRAN=true
before_install:
- echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
after_success:
r_binary_packages:
notifications:
  email:
    on_success: change
    on_failure: always
notifications:
  slack: cocolab-stanford:xTQOmr4PbzzB3TjQa4BGRGyp
